jobs:
  test:
    uses: ./.github/workflows/build-platform.yml
    with:
      version: "1.0.0"
      shortened_version: "1.0"
      tags: "test"
      build_id: "local-123"
      is_release: "false"
    secrets:
      GH_TOKEN: "dummy"
      GITHUB_TOKEN: "dummy"
      HARBOR_USERNAME: "dummy"
      HARBOR_CLI_SECRET: "dummy"
      REGISTRY_USERNAME: "dummy"
      REGISTRY_PASSWORD: "dummy"